cmdb/urls.py
# coding=utf-8
#

from django.conf.urls import url

from host import *  # host, a10

from dk import *


urlpatterns = [


    url(r'^docker/info/(?P<pk>\d+)/', info, name="dockerinfo"),
    url(r'^docker/image/(?P<pk>\d+)/info/', image_info, name="docker_image_info"),
    url(r'^docker/image/(?P<pk>\d+)/rm/', image_rm, name="docker_image_rm"),
    url(r'^docker/image/(?P<pk>\d+)/', image, name="dockerimage"),
    url(r'^docker/image/', image, name="dockerimage"),
    url(r'^docker/container/(?P<pk>\d+)/info/', container_info, name="docker_container_info"),
    url(r'^docker/container/(?P<pk>\d+)/rm/', container_rm, name="docker_container_rm"),
    url(r'^docker/container/(?P<pk>\d+)/add/', container_add, name="docker_container_add"),
    url(r'^docker/container/(?P<pk>\d+)/', container, name="dockercontainer"),
    url(r'^docker/container/', container, name="dockercontainer"),
    url(r'^docker', DockerList.as_view(), name="dockerlist"),


]

dock/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

cmdb/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
# from django.utils.timezone import now, localdate
from datetime import datetime, timedelta

from django.core.cache import cache
from django import template
from django.contrib.auth.models import User, Group
import traceback
from Crypto.Cipher import AES
import base64
import paramiko
import docker
import os
import urlparse


class Docker(models.Model):
    # 容器宿主机、物理机，必需已开启监听端口(swarm)，用于cmdb连接远程API
    # CMDB不使用swarm、docker service功能，因网络只能为overlay无法自定义配置

    name = models.CharField(max_length=100, verbose_name=u"标识名称")
    """
    host = models.CharField(verbose_name='宿主机', max_length=50, default='.docker.sdj',
        help_text='Docker容器宿主机、物理机域名，比如xxx.docker.sdj，<br/>\
        如果未开启tls证书验证，则可直接填写IP，否则请填写域名<br/>\
        因ssl证书使用IP时，需每台Docker物理机都配置生成相应IP证书，<br/>\
        为简化配置处理，统一使用泛域名*.docker.sdj SSL证书<br/>')
    """
    ip = models.GenericIPAddressField(u"宿主机IP", max_length=15)
    port = models.IntegerField(verbose_name='Docker端口', default=2375)
    tls = models.BooleanField(verbose_name='TLS', default=True, help_text='Docker-API不会进行安全验证，任意接入的客户端都能进行所有操作<br/>为安全需配置TLS，客户端使用证书访问API接口')
    # ver = models.CharField(max_length=20, verbose_name=u"Docker版本", help_text='Docker服务端版本', null=True, blank=True)
    text = models.TextField(u"备注信息", default='', null=True, blank=True)

    class Meta:
        verbose_name = '容器宿主机'

    def __unicode__(self):
        return '%s (%s)' % (self.name, self.ip)

    def ip2host(self):
        # 将IP转换为虚拟构造的域名，用于泛域名*.docker.sdj SSL证书验证
        return '%s.docker.sdj' % self.ip.replace('.', '_')

    @property
    def client(self):
        tls = 1 if self.tls else ''  # docker.utils.utils.kwargs_from_env
        try:
            cli = docker.from_env(
                timeout=10,
                environment={
                    'DOCKER_HOST': 'tcp://%s:%d' % (self.ip2host(), self.port),
                    'DOCKER_TLS_VERIFY': tls
                }
            )
        except docker.errors.TLSParameterError as e:
            print 'SSL证书不存在？', 'DOCKER_TLS_VERIFY:', tls
            raise e

        cli.docker = self
        return cli

cmdb/templates/docker_container.html
{% extends "_base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block  title %}容器管理{% endblock %}

{% block left %}
    {% include "_left.html" with cmdb_docker_container_active="active" %}
{% endblock left %}


{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">主页</a>
                </li>
                <li>
                    <a href="{% url 'cmdb:dockerlist' %}">Docker管理</a>
                </li>
                <li class="active">
                    <strong>容器管理 - {{ client.docker }}</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row wrapper wrapper-content animated fadeInRight">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="col-md-8 form-inline">
                        <label class="text-success">宿主机:</label>
                        
                        <select id="docker" class="form-control">
                            {% if not client %}<option value="">------</option>{% endif %}
                            {% for row in dockers %}
                            <option value="{{ row.id }}" {% if row == client.docker %}selected{% endif %}>{{ row }}</option>
                            {% endfor %}
                        </select>

                    </div>


                </div>
                <div class="ibox-content">
                    {% if error %}
                    {{ error }}
                    {% elif client %}
                    <a href="{% url 'cmdb:docker_container_add' client.docker.id %}" class="btn btn-primary"> 添加</a>
                    <a class="btn btn-danger" id="delall">批量删除</a>

                    <table class="table table-striped table-bordered table-hover dataTables-example" id="tb">
                        <thead>
                            <tr>
                                <th><input type="checkbox" id="CheckedAll"></th>
                                <th class="col-xs-4">名称</th>
                                <th class="col-xs-2">镜像</th>
                                <th class="col-xs-1">容器IP</th>
                                <th class="col-xs-1">状态</th>
                                <th class="col-lg-1">创建</th>
                                <th class="col-xs-3">操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in cons %}
                            <tr>
                                <td><input type="checkbox" value="{{ i.id }}"  name="id"></td>
                                <td>{{ i.name }}</td>
                                <td>{{ i.image }}</td>
                                <td>{{ i.ip }}</td>
                                <td>{{ i.status }}</td>
                                <td>{{ i.time }}</td>
                                {# <td>{{ i.runtime }}</td> #}

                                <td>
                                    <button type="button" class="btn btn-info btn-xs">启动</button>
                                    <button type="button" class="btn btn-warning btn-xs">停止</button>
                                    <button type="button" class="btn btn-primary btn-xs">详情</button>
                                    <button type="button" class="btn btn-success btn-xs">日志</button>
                                    <button type="button" class="btn btn-danger btn-xs">删除</button>
                                </td>
                            </tr>
                            {% endfor %}


                        </tbody>

                    </table>
                    {% else %}
                    请选择宿主机/物理机
                    {% endif %}

                    
                    <div class="panel panel-success" style="display:none" id="server_div">
                        <div class="panel-heading">
                            <h5>操作返回</h5>
                        </div>
                        <div class="panel-body">
                        <span id="server"></span>
                        <textarea id="server_msg" readonly style="width:100%;" rows="5">{{ text }}</textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>

{% endblock %}


{% block footer-js %}
    <script>
        function conn_docker(url, textarea_height){
            $.ajax({
                url: url,
                type: 'GET',
                timeout: 20000,
                error: function(){
                    $("#server_msg").html('<option value="">网站连接失败！请联系CMDB管理员</option>');
                },
                success: function(msg_html){
                    // json格式化
                    // console.log(msg_html);
                    try{
                        var msg_html = JSON.stringify(JSON.parse(msg_html), null, 4);
                    }finally{
                        $('#server_msg').val(msg_html);
                        // console.log(txt);
                        $('#server_msg')[0].style.minHeight= textarea_height;
                    } 
                }
            });
        };

        $(document).ready(function(){

            $('#docker').change(function() {
                if (this.value) {
                    console.log(this.value);
                    window.location.href="{% url 'cmdb:dockercontainer' %}"+this.value+"/"
                }
            });

            {% if client %}

            // $( ".btn-danger.btn-xs" ).click()
            $('#tb').on('click', 'button', function (e) {
                console.log($(this));
                var url="{% url 'cmdb:docker_container_info' client.docker.id %}?id="+this.parentElement.parentElement.children[0].children[0].value;
                var textarea_height="400px";
                if (this.className=="btn btn-danger btn-xs") {
                    if(! window.confirm('确认删除容器？')){
                        return false;
                    }
                    var url="{% url 'cmdb:docker_container_rm' client.docker.id %}?id="+this.parentElement.parentElement.children[0].children[0].value;
                    textarea_height="100px";
                } else if (this.className=="btn btn-primary btn-xs") {
                    url=url+"&info=attrs";
                } else if (this.className=="btn btn-success btn-xs") {
                    url=url+"&info=logs";
                } else if (this.className=="btn btn-info btn-xs") {
                    url=url+"&info=start";
                    textarea_height="100px";
                } else if (this.className=="btn btn-warning btn-xs") {
                    url=url+"&info=stop";
                    textarea_height="100px";
                }

                $("#server_div").show();
                $("#server").text(this.parentElement.parentElement.children[1].textContent+" "+this.textContent);
                conn_docker(url, textarea_height);

            });


            $("#delall").click(function(){
                var container_ids = '';
                var cs=document.getElementsByName('id');
                for (i=0; i < cs.length; i++) {
                    if (cs[i].checked) {
                        container_ids = container_ids+cs[i].value+',';
                        // console.log(cs[i].value);
                    }
                }
                if (! container_ids) {return false;}
                if(! window.confirm('确认批量删除容器？')){
                    return false;
                }
                var url="{% url 'cmdb:docker_container_rm' client.docker.id %}?id="+container_ids;
                console.log(container_ids);
                $("#server_div").show();
                $("#server").text("批量删除容器");
                conn_docker(url, "100px");
            });
            {% endif %}

        });


    </script>
{% endblock footer-js %}



cmdb/templates/docker_container_add.html
{% extends "_base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block  title %}容器管理{% endblock %}

{% block left %}
    {% include "_left.html" with cmdb_docker_container_active="active" %}
{% endblock left %}


{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">主页</a>
                </li>
                <li>
                    <a href="{% url 'cmdb:dockerlist' %}">Docker管理</a>
                </li>
                <li>
                    <a href="{% url 'cmdb:dockercontainer' client.docker.id %}">容器管理 - {{ client.docker }}</a>
                </li>
                <li class="active">
                    <strong>新建容器</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row wrapper wrapper-content animated fadeInRight">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>创建容器</h5>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" class="form-horizontal" action=""
                        method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if form.errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.errors }}
                            </div>
                        {% endif %}

                        <!-- <div class="form-group">
                            <label class="col-md-2 control-label" for="id_host">宿主机</label>
                            <div class="col-md-9">
                                <span class="form-control">{{ client.docker }}</span>
                            </div>
                        </div> -->

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">容器名称</label>
                            <div class="col-md-9">
                                <input type="text" name="name" value="{{ form.data.name }}" required="" maxlength="100" placeholder="容器名称" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">使用镜像</label>
                            <div class="col-md-9">
                                <select name="image" required="" class="form-control">
                                    {% for row in imgs %}
                                    <option value="{{ row.name }}" {% if row.name == form.data.image %}selected{% endif %}>{{ row.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">使用网络</label>
                            <div class="col-md-9">
                                <select name="network" required="" class="form-control">
                                    {% for row in nets %}
                                    <option value="{{ row.name }}" {% if row.name == form.data.network %}selected{% endif %}>{{ row.type }} -- {{ row.name }} ({{ row.subnet }})</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">容器IP</label>
                            <div class="col-md-9">
                                <input type="text" name="ip" value="{{ form.data.ip }}" maxlength="100" placeholder="未填写时，将自动根据所选网络进行分配" class="form-control">
                                <div class="help-block">若未填IP，可能导致系统自动设置的IP与其它宿主机的容器IP冲突！</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">挂载目录</label>
                            <div class="col-md-9">
                                <input type="text" name="volumes" value="{{ form.data.volumes }}" maxlength="300" placeholder="/var/www:/mnt/vol1:ro, /home/app/:/mnt/vol2" class="form-control">
                                <div class="help-block">比如只读> 宿目录:容器路径:ro，多个挂载使用逗号间隔</div>
                            </div>

                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">启动命令</label>
                            <div class="col-md-9">
                                <input type="text" name="command" value="{{ form.data.command }}" placeholder="自定义运行命令" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label" for="id_state">&nbsp;</label>
                            <div class="col-md-9">
                                <div class="checkbox">
                                    <label><input type="checkbox" name="start" checked id="id_start">创建后启动容器</label>
                                </div>

                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                <button class="btn btn-primary" type="submit">提交</button>
                                <button class="btn btn-white" type="reset">重置</button>
                            </div>
                        </div>

                    </form>


                </div>
            </div>
        </div>


    </div>

{% endblock %}


{% block footer-js %}
    <script>
        function conn_docker(url, textarea_height){
            $.ajax({
                url: url,
                type: 'GET',
                timeout: 20000,
                error: function(){
                    $("#server_msg").html('<option value="">网站连接失败！请联系CMDB管理员</option>');
                },
                success: function(msg_html){
                    // json格式化
                    // console.log(msg_html);
                    try{
                        var msg_html = JSON.stringify(JSON.parse(msg_html), null, 4);
                    }finally{
                        $('#server_msg').val(msg_html);
                        // console.log(txt);
                        $('#server_msg')[0].style.minHeight= textarea_height;
                    } 
                }
            });
        };

        $(document).ready(function(){

            $('#docker').change(function() {
                if (this.value) {
                    console.log(this.value);
                    window.location.href="{% url 'cmdb:dockercontainer' %}"+this.value+"/"
                }
            });

            {% if client %}

            // $( ".btn-danger.btn-xs" ).click()
            $('#tb').on('click', 'button', function (e) {
                console.log($(this));
                var url="{% url 'cmdb:docker_container_info' client.docker.id %}?id="+this.parentElement.parentElement.children[0].children[0].value;
                var textarea_height="400px";
                if (this.className=="btn btn-danger btn-xs") {
                    if(! window.confirm('确认删除容器？')){
                        return false;
                    }
                    var url="{% url 'cmdb:docker_container_rm' client.docker.id %}?id="+this.parentElement.parentElement.children[0].children[0].value;
                    textarea_height="100px";
                } else if (this.className=="btn btn-primary btn-xs") {
                    url=url+"&info=attrs";
                } else if (this.className=="btn btn-success btn-xs") {
                    url=url+"&info=logs";
                } else if (this.className=="btn btn-info btn-xs") {
                    url=url+"&info=start";
                    textarea_height="100px";
                } else if (this.className=="btn btn-warning btn-xs") {
                    url=url+"&info=stop";
                    textarea_height="100px";
                }

                $("#server_div").show();
                $("#server").text(this.parentElement.parentElement.children[1].textContent+" "+this.textContent);
                conn_docker(url, textarea_height);

            });


            $("#delall").click(function(){
                var container_ids = '';
                var cs=document.getElementsByName('id');
                for (i=0; i < cs.length; i++) {
                    if (cs[i].checked) {
                        container_ids = container_ids+cs[i].value+',';
                        // console.log(cs[i].value);
                    }
                }
                if (! container_ids) {return false;}
                if(! window.confirm('确认批量删除容器？')){
                    return false;
                }
                var url="{% url 'cmdb:docker_container_rm' client.docker.id %}?id="+container_ids;
                console.log(container_ids);
                $("#server_div").show();
                $("#server").text("批量删除容器");
                conn_docker(url, "100px");
            });
            {% endif %}

        });


    </script>
{% endblock footer-js %}



cmdb/templates/docker_image.html
{% extends "_base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block  title %}镜像管理{% endblock %}

{% block left %}
    {% include "_left.html" with cmdb_docker_image_active="active" %}
{% endblock left %}


{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">主页</a>
                </li>
                <li>
                    <a href="{% url 'cmdb:dockerlist' %}">Docker管理</a>
                </li>
                <li class="active">
                    <strong>镜像管理</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row wrapper wrapper-content animated fadeInRight">
        <div class="row col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="col-md-8 form-inline">
                        <label class="text-success">宿主机:</label>
                        
                        <select id="docker" class="form-control">
                            {% if not client %}<option value="">------</option>{% endif %}
                            {% for row in dockers %}
                            <option value="{{ row.id }}" {% if row == client.docker %}selected{% endif %}>{{ row }}</option>
                            {% endfor %}
                        </select>

                    </div>


                </div>
                <div class="ibox-content">
                    {% if error %}
                    {{ error }}
                    {% elif client %}
                    <table class="table table-striped table-bordered table-hover dataTables-example" id="tb_images">
                        <thead>
                            <tr>
                                <th>名称</th>
                                <th class="col-xs-1">版本</th>
                                <th class="col-lg-1">创建</th>
                                <th class="col-xs-1">大小</th>
                                <th class="col-xs-2">操作</th>
                            </tr>
                        </thead>
                        <tbody>
                        
                            {% for i in imgs %}
                            <tr>
                                <td>{{ i.name }}</td>
                                <td>{{ i.ver }}</td>
                                <td>{{ i.time }}</td>
                                <td>{{ i.size|filesizeformat }}</td>

                                <td id="{{ i.id }}">
                                    <button type="button" class="btn btn-primary btn-xs">详情</button>
                                    <button type="button" class="btn btn-success btn-xs">历史</button>
                                    <button type="button" class="btn btn-danger btn-xs">删除</button>

                                </td>
                            </tr>
                            {% endfor %}


                        </tbody>

                    </table>
                    {% else %}
                    请选择宿主机/物理机
                    {% endif %}

                    
                    <div class="panel panel-success" style="display:none" id="server_div">
                        <div class="panel-heading">
                            <h5>操作返回</h5>
                        </div>
                        <div class="panel-body">
                        <span id="server"></span>
                        <textarea id="server_msg" readonly style="width:100%;" rows="5">{{ text }}</textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>

{% endblock %}


{% block footer-js %}
    <script>
        $(document).ready(function(){

            $('#docker').change(function() {
                if (this.value) {
                    console.log(this.value);
                    window.location.href="{% url 'cmdb:dockerimage' %}"+this.value+"/"
                }
            });

            {% if client %}
            // $( ".btn-danger.btn-xs" ).click()
            $('#tb_images').on('click', 'button', function (e) {
                // console.log($(this));
                var url="{% url 'cmdb:docker_image_info' client.docker.id %}?img="+this.parentElement.id;
                var textarea_height="400px";
                if (this.className=="btn btn-danger btn-xs") {
                    if(! window.confirm('确认删除镜像？\n依赖当前镜像运行的容器也将一起删除！')){
                        return false;
                    }
                    var url="{% url 'cmdb:docker_image_rm' client.docker.id %}?img="+this.parentElement.id;
                    textarea_height="100px";
                } else if (this.className=="btn btn-primary btn-xs") {
                    url=url+"&info=attrs";
                } else if (this.className=="btn btn-success btn-xs") {
                    url=url+"&info=history";
                }
                $("#server_div").show();
                $("#server").text(this.parentElement.parentElement.children[0].textContent+" "+this.textContent);
                $.ajax({
                    url: url,
                    type: 'GET',
                    timeout: 10000,
                    error: function(){
                        $("#server_msg").html('<option value="">网站连接失败！请联系CMDB管理员</option>');
                    },
                    success: function(msg_html){
                        // json格式化
                        // console.log(msg_html);
                        var result = JSON.stringify(JSON.parse(msg_html), null, 4);
                        $('#server_msg').val(result);
                        // console.log(txt);
                        $('#server_msg')[0].style.minHeight= textarea_height;
                    }
                });
            });
            {% endif %}

        });


    </script>
{% endblock footer-js %}



cmdb/templates/docker_info.html
{% extends "_base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block  title %}Docker信息{% endblock %}

{% block left %}
    {% include "_left.html" with cmdb_docker_active="active" %}
{% endblock left %}


{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">主页</a>
                </li>
                <li>
                    <a href="{% url 'cmdb:dockerlist' %}">Docker管理</a>
                </li>
                <li class="active">
                    <strong>Docker信息</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row wrapper wrapper-content animated fadeInRight">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>{{ dk }}</h5>
                </div>
                <div class="ibox-content">

                    <textarea id="detail" readonly="readonly" style="width:100%;" rows="50">{{ text }}</textarea>


                </div>
            </div>
        </div>

    </div>

{% endblock %}



{% block footer-js %}

    <script>
        var json = $('#detail').val();
        var result = JSON.stringify(JSON.parse(json), null, 4);
        $('#detail').val(result);
    </script>


{% endblock footer-js %}
